spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tmc_db
    username: tmc_user
    password: TMC@2025
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true